ERROR 2025-10-18 10:09:07,063 error_handlers 3640 123145585475584 Unhandled Exception - ID: e8104e3f-a827-481b-8fb6-c6e48e6b7dec, Path: /company/register/, User: 1, Exception: SyntaxError: unexpected character after line continuation character (notification_service.py, line 246)
Traceback (most recent call last):
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/core/views.py", line 36, in company_register
    return render(request, 'core/company_register.html', {'form': form})
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/base.py", line 169, in render
    with context.bind_template(self):
         ~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/local/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/contextlib.py", line 141, in __enter__
    return next(self.gen)
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/context.py", line 256, in bind_template
    processors = template.engine.template_context_processors + self._processors
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/engine.py", line 118, in template_context_processors
    return tuple(import_string(path) for path in context_processors)
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/engine.py", line 118, in <genexpr>
    return tuple(import_string(path) for path in context_processors)
                 ~~~~~~~~~~~~~^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/utils/module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "/usr/local/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/core/signals.py", line 7, in <module>
    from .notification_service import NotificationService
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/core/notification_service.py", line 246
    message=f'Your role in {membership.company.name} has been changed from {old_role.name if old_role else \"No Role\"} to {new_role.name} by {changed_by.get_full_name()}.',
                                                                                                            ^
SyntaxError: unexpected character after line continuation character
ERROR 2025-10-18 10:10:19,698 error_handlers 4810 123145566969856 Unhandled Exception - ID: 79750ecc-ec78-4617-ba05-8334e4fec40b, Path: /company/register/, User: 1, Exception: NoReverseMatch: Reverse for 'profile' not found. 'profile' is not a valid view function or pattern name.
Traceback (most recent call last):
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/core/views.py", line 36, in company_register
    return render(request, 'core/company_register.html', {'form': form})
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'profile' not found. 'profile' is not a valid view function or pattern name.
ERROR 2025-10-18 10:20:29,280 views 13746 123145354526720 Dashboard error for user 2: no such column: projects_project.company_id
Traceback (most recent call last):
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: projects_project.company_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/dashboard/views.py", line 40, in dashboard
    total_projects = Project.objects.filter(company=current_company).count()
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/models/query.py", line 604, in count
    return self.query.get_count(using=self.db)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/models/sql/query.py", line 644, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/models/sql/query.py", line 626, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: projects_project.company_id
ERROR 2025-10-18 10:20:54,095 views 13746 123145354526720 Dashboard error for user 2: no such column: projects_project.company_id
Traceback (most recent call last):
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: projects_project.company_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/dashboard/views.py", line 40, in dashboard
    total_projects = Project.objects.filter(company=current_company).count()
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/models/query.py", line 604, in count
    return self.query.get_count(using=self.db)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/models/sql/query.py", line 644, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/models/sql/query.py", line 626, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: projects_project.company_id
ERROR 2025-10-18 10:21:08,195 error_handlers 13746 123145354526720 Unhandled Exception - ID: 0ca10974-6276-41aa-a9d6-78e8f6b7d1d4, Path: /profile/, User: 2, Exception: TemplateSyntaxError: Could not parse the remainder: ':status='in_progress'.count' from 'user.project_set.filter:status='in_progress'.count'
Traceback (most recent call last):
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/contrib/auth/decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/core/views.py", line 112, in profile_view
    return render(request, 'core/profile.html', {
        'form': form,
    ...<2 lines>...
        'memberships': memberships
    })
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/base.py", line 489, in parse
    raise self.error(token, e)
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/base.py", line 487, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/base.py", line 609, in compile_filter
    return FilterExpression(token, self)
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/base.py", line 710, in __init__
    raise TemplateSyntaxError(
    ...<2 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ':status='in_progress'.count' from 'user.project_set.filter:status='in_progress'.count'
ERROR 2025-10-18 10:23:37,159 views 18353 123145450278912 Dashboard error for user 2: no such column: expenses_expense.created_by_id
Traceback (most recent call last):
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: expenses_expense.created_by_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/dashboard/views.py", line 133, in dashboard
    return render(request, 'dashboard/dashboard.html', context)
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 199, in render
    len_values = len(values)
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/models/query.py", line 366, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/models/query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: expenses_expense.created_by_id
ERROR 2025-10-18 11:09:33,483 views 54344 123145554382848 Dashboard error for user 2: no such column: expenses_expense.created_by_id
Traceback (most recent call last):
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: expenses_expense.created_by_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/dashboard/views.py", line 133, in dashboard
    return render(request, 'dashboard/dashboard.html', context)
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 199, in render
    len_values = len(values)
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/models/query.py", line 366, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/models/query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: expenses_expense.created_by_id
ERROR 2025-10-18 11:09:59,506 views 54344 123145554382848 Dashboard error for user 2: no such column: expenses_expense.created_by_id
Traceback (most recent call last):
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: expenses_expense.created_by_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/dashboard/views.py", line 133, in dashboard
    return render(request, 'dashboard/dashboard.html', context)
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 199, in render
    len_values = len(values)
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/models/query.py", line 366, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/models/query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: expenses_expense.created_by_id
CRITICAL 2025-10-18 14:00:09,924 error_middleware 3423 123145422487552 [DB-09CE] OperationalError: no such column: core_role.is_team_member | Request: GET /company/settings/ | User: crystalbluetech@gmail.com
CRITICAL 2025-10-18 14:00:09,924 error_middleware 3423 123145422487552 Traceback:
Traceback (most recent call last):
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/models/fields/related_descriptors.py", line 243, in __get__
    rel_obj = self.field.get_cached_value(instance)
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/models/fields/mixins.py", line 37, in get_cached_value
    return instance._state.fields_cache[self.cache_name]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'role'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: core_role.is_team_member

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/contrib/auth/decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/core/views.py", line 565, in company_settings_view
    if not membership.is_company_admin():
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/core/models.py", line 140, in is_company_admin
    return self.role and self.role.is_admin
           ^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/models/fields/related_descriptors.py", line 261, in __get__
    rel_obj = self.get_object(instance)
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/models/fields/related_descriptors.py", line 224, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
           ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/models/query.py", line 629, in get
    num = len(clone)
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/models/query.py", line 366, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/models/query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/muhammadibnsalyhu/Desktop/construction_expense_tracker/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: core_role.is_team_member

ERROR 2025-10-19 06:51:03,053 error_middleware 79554 123145467932672 [AU-2118] PermissionDenied:  | Request: GET /admin/core/company/ | User: superadmin
ERROR 2025-10-19 06:51:13,981 error_middleware 79554 123145467932672 [AU-59CB] PermissionDenied:  | Request: GET /admin/core/company/ | User: superadmin
ERROR 2025-10-19 08:21:42,710 error_middleware 52315 123145524187136 [AU-C1F1] PermissionDenied:  | Request: GET /admin/core/company/ | User: msa
ERROR 2025-10-19 08:39:46,034 error_middleware 83724 123145349607424 [AU-5E60] PermissionDenied:  | Request: GET /admin/core/company/ | User: msa
ERROR 2025-10-19 08:41:15,001 error_middleware 83724 123145349607424 [AU-4BF0] PermissionDenied:  | Request: GET /admin/auth/user/ | User: msa
ERROR 2025-10-19 08:56:59,945 error_middleware 3381 123145452265472 [AU-5144] PermissionDenied:  | Request: GET /admin/core/company/ | User: msa
